# configs/root_finding.yaml

# Configuration for the Himmelblau function - a classic 2D test function
# The function has 4 known minima at:
# (3.0, 2.0), (-2.805118, 3.131312), (-3.779310, -3.283186), and (3.584428, -1.848126)

# Function to optimize
function: 2d_himmelblau

# Methods that handle 2D optimization well
methods:
  - bfgs
  # - newton
  # - newton_hessian

# Initial points - starting near but not at one of the minima
x0: [2.5, 1.5]

# Algorithm parameters - tighter tolerance for precise results
tol: 1.0e-10
max_iter: 75

# Visualization settings
xrange: [-6, 6]  # Covers the range where all minima exist
viz_3d: false     # Enable 3D visualization since this is a 2D function
no_viz: true      

# Step length parameters - using a more sophisticated line search
step_length_method: wolfe
step_length_params: {"c1": 1.0e-4, "c2": 0.9, "alpha_init": 1.0} 